[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/sweettea-io/envdecode"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"